server {
    listen 80;
    server_name siteweb2.com;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name siteweb2.com;

    ssl_certificate /usr/local/openresty/nginx/conf/domains/siteweb2.com/certs/fullchain.pem;
    ssl_certificate_key /usr/local/openresty/nginx/conf/domains/siteweb2.com/certs/privkey.pem;
    
    include /usr/local/openresty/nginx/conf/snippets/ssl-params.conf;
    include /usr/local/openresty/nginx/conf/snippets/error-pages.conf;
    include /usr/local/openresty/nginx/conf/snippets/proxy-params.conf;

    # Pages d'erreur personnalisées
    location = /404.html {
        root /usr/local/openresty/nginx/html;
        internal;
    }

    location = /50x.html {
        root /usr/local/openresty/nginx/html;
        internal;
    }

    location / {
        # ✅ UTILISE la zone anti-DDOS
        limit_req zone=general burst=50 nodelay;
        limit_conn addr 40;
        
        proxy_pass http://XX.XX.XX.XX:XXXX/;
        #IP DE VOTRE CLIENT VPN VyOS, PORT DU WAF
    }
}
