# Configuration pour sousdomaine.siteweb2.com (Attention configuration simple sans HTTPS, voir siteweb1 pour exemple de sous domaine avec https)
server {
    listen 80;
    server_name sousdomaine.siteweb2.com;

    # Pages d'erreur personnalisées
    location = /404.html {
        root /usr/local/openresty/nginx/html;
        internal;
    }

    location = /50x.html {
        root /usr/local/openresty/nginx/html;
        internal;
    }

    location / {
        proxy_pass http://X.X.X.X:XXXX/;
        #IP DE VOTRE CLIENT VPN VyOS+PORT DU WAF
        include /usr/local/openresty/nginx/conf/snippets/proxy-params.conf;
    }

}
